/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 127
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym__newline = 2,
  anon_sym_GT_GT_GT = 3,
  anon_sym_AT = 4,
  anon_sym_COLON = 5,
  anon_sym_STAR = 6,
  anon_sym_u20ac = 7,
  anon_sym_DEFAULT = 8,
  anon_sym_COMMAND = 9,
  anon_sym_UPDATE_COMMAND = 10,
  anon_sym_QUEUE_COMMAND = 11,
  sym_address = 12,
  sym_command_arg = 13,
  anon_sym_LT = 14,
  anon_sym_SEMI = 15,
  anon_sym_GT = 16,
  aux_sym_group_override_token1 = 17,
  sym_shuttle_content = 18,
  anon_sym_COMMA = 19,
  anon_sym_PLUS = 20,
  anon_sym_DASH = 21,
  anon_sym_EQ = 22,
  aux_sym_arg_name_token1 = 23,
  sym_number = 24,
  sym_additional_config = 25,
  sym_effect_id = 26,
  sym_source_file = 27,
  sym__line = 28,
  sym__statement = 29,
  sym_group_filter = 30,
  sym_synth_header = 31,
  sym_selected = 32,
  sym_effect_definition = 33,
  sym_default_statement = 34,
  sym_command = 35,
  sym_command_type = 36,
  sym_track = 37,
  sym_track_metadata = 38,
  sym_group_override = 39,
  sym_arg_list = 40,
  sym_arg = 41,
  sym_operator = 42,
  sym_arg_name = 43,
  sym_ref = 44,
  sym_instrument_name = 45,
  sym_group_name = 46,
  sym_effect_type = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_group_filter_repeat1 = 49,
  aux_sym_command_repeat1 = 50,
  aux_sym_arg_list_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [anon_sym_GT_GT_GT] = ">>>",
  [anon_sym_AT] = "@",
  [anon_sym_COLON] = ":",
  [anon_sym_STAR] = "*",
  [anon_sym_u20ac] = "\u20ac",
  [anon_sym_DEFAULT] = "DEFAULT",
  [anon_sym_COMMAND] = "COMMAND",
  [anon_sym_UPDATE_COMMAND] = "UPDATE_COMMAND",
  [anon_sym_QUEUE_COMMAND] = "QUEUE_COMMAND",
  [sym_address] = "address",
  [sym_command_arg] = "command_arg",
  [anon_sym_LT] = "<",
  [anon_sym_SEMI] = ";",
  [anon_sym_GT] = ">",
  [aux_sym_group_override_token1] = "group_override_token1",
  [sym_shuttle_content] = "shuttle_content",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ] = "=",
  [aux_sym_arg_name_token1] = "arg_name_token1",
  [sym_number] = "number",
  [sym_additional_config] = "additional_config",
  [sym_effect_id] = "effect_id",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_group_filter] = "group_filter",
  [sym_synth_header] = "synth_header",
  [sym_selected] = "selected",
  [sym_effect_definition] = "effect_definition",
  [sym_default_statement] = "default_statement",
  [sym_command] = "command",
  [sym_command_type] = "command_type",
  [sym_track] = "track",
  [sym_track_metadata] = "track_metadata",
  [sym_group_override] = "group_override",
  [sym_arg_list] = "arg_list",
  [sym_arg] = "arg",
  [sym_operator] = "operator",
  [sym_arg_name] = "arg_name",
  [sym_ref] = "ref",
  [sym_instrument_name] = "instrument_name",
  [sym_group_name] = "group_name",
  [sym_effect_type] = "effect_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_group_filter_repeat1] = "group_filter_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [anon_sym_GT_GT_GT] = anon_sym_GT_GT_GT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_u20ac] = anon_sym_u20ac,
  [anon_sym_DEFAULT] = anon_sym_DEFAULT,
  [anon_sym_COMMAND] = anon_sym_COMMAND,
  [anon_sym_UPDATE_COMMAND] = anon_sym_UPDATE_COMMAND,
  [anon_sym_QUEUE_COMMAND] = anon_sym_QUEUE_COMMAND,
  [sym_address] = sym_address,
  [sym_command_arg] = sym_command_arg,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_group_override_token1] = aux_sym_group_override_token1,
  [sym_shuttle_content] = sym_shuttle_content,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_arg_name_token1] = aux_sym_arg_name_token1,
  [sym_number] = sym_number,
  [sym_additional_config] = sym_additional_config,
  [sym_effect_id] = sym_effect_id,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_group_filter] = sym_group_filter,
  [sym_synth_header] = sym_synth_header,
  [sym_selected] = sym_selected,
  [sym_effect_definition] = sym_effect_definition,
  [sym_default_statement] = sym_default_statement,
  [sym_command] = sym_command,
  [sym_command_type] = sym_command_type,
  [sym_track] = sym_track,
  [sym_track_metadata] = sym_track_metadata,
  [sym_group_override] = sym_group_override,
  [sym_arg_list] = sym_arg_list,
  [sym_arg] = sym_arg,
  [sym_operator] = sym_operator,
  [sym_arg_name] = sym_arg_name,
  [sym_ref] = sym_ref,
  [sym_instrument_name] = sym_instrument_name,
  [sym_group_name] = sym_group_name,
  [sym_effect_type] = sym_effect_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_group_filter_repeat1] = aux_sym_group_filter_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u20ac] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DEFAULT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMAND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UPDATE_COMMAND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QUEUE_COMMAND] = {
    .visible = true,
    .named = false,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [sym_command_arg] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_group_override_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_shuttle_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_arg_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_additional_config] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_id] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_group_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_synth_header] = {
    .visible = true,
    .named = true,
  },
  [sym_selected] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_default_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_command_type] = {
    .visible = true,
    .named = true,
  },
  [sym_track] = {
    .visible = true,
    .named = true,
  },
  [sym_track_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_group_override] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_name] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_instrument_name] = {
    .visible = true,
    .named = true,
  },
  [sym_group_name] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_filter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 5,
  [12] = 12,
  [13] = 6,
  [14] = 12,
  [15] = 10,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 17,
  [22] = 22,
  [23] = 22,
  [24] = 20,
  [25] = 22,
  [26] = 26,
  [27] = 27,
  [28] = 26,
  [29] = 29,
  [30] = 27,
  [31] = 29,
  [32] = 26,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 36,
  [41] = 37,
  [42] = 39,
  [43] = 27,
  [44] = 29,
  [45] = 33,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 50,
  [53] = 53,
  [54] = 54,
  [55] = 53,
  [56] = 56,
  [57] = 57,
  [58] = 49,
  [59] = 59,
  [60] = 39,
  [61] = 48,
  [62] = 37,
  [63] = 36,
  [64] = 56,
  [65] = 65,
  [66] = 66,
  [67] = 20,
  [68] = 50,
  [69] = 53,
  [70] = 56,
  [71] = 71,
  [72] = 48,
  [73] = 49,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 71,
  [80] = 80,
  [81] = 81,
  [82] = 74,
  [83] = 66,
  [84] = 65,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 91,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 98,
  [103] = 99,
  [104] = 101,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 109,
  [120] = 120,
  [121] = 121,
  [122] = 113,
  [123] = 123,
  [124] = 109,
  [125] = 105,
  [126] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 74,
        '\r', 1,
        '#', 73,
        '*', 78,
        '+', 137,
        ',', 136,
        '-', 138,
        '/', 54,
        ':', 77,
        ';', 88,
        '<', 87,
        '=', 139,
        '>', 90,
        '@', 76,
        'C', 40,
        'D', 25,
        'Q', 47,
        'U', 43,
      );
      if (lookahead == '\\') SKIP(56);
      if (lookahead == 0x20ac) ADVANCE(79);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(74);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(86);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 74,
        '\r', 1,
        '#', 72,
        '*', 78,
        '/', 54,
        '<', 87,
        '>', 12,
        '@', 76,
        'C', 123,
        'D', 108,
        'Q', 130,
        'U', 126,
        '\\', 92,
        0x20ac, 79,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(134);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 74,
        '\r', 149,
        '#', 73,
        '*', 78,
        '+', 137,
        '-', 138,
        ':', 77,
        '=', 139,
        '\\', 150,
        '\t', 144,
        ' ', 144,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 74,
        '\r', 149,
        '#', 73,
        '*', 78,
        '+', 137,
        '-', 138,
        '=', 139,
        '\\', 152,
        '\t', 145,
        ' ', 145,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == ',') ADVANCE(136);
      if (lookahead == '\\') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(146);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == ',') ADVANCE(136);
      if (lookahead == '\\') ADVANCE(156);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(158);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(148);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(2);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(49);
      END_STATE();
    case 11:
      if (lookahead == '\n') SKIP(49);
      if (lookahead == '\r') SKIP(10);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(75);
      END_STATE();
    case 14:
      if (lookahead == 'A') ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead == 'A') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(46);
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(38);
      END_STATE();
    case 18:
      if (lookahead == 'A') ADVANCE(39);
      END_STATE();
    case 19:
      if (lookahead == 'C') ADVANCE(41);
      END_STATE();
    case 20:
      if (lookahead == 'C') ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == 'D') ADVANCE(81);
      END_STATE();
    case 22:
      if (lookahead == 'D') ADVANCE(83);
      END_STATE();
    case 23:
      if (lookahead == 'D') ADVANCE(82);
      END_STATE();
    case 24:
      if (lookahead == 'D') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'E') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'E') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 'E') ADVANCE(48);
      END_STATE();
    case 28:
      if (lookahead == 'E') ADVANCE(52);
      END_STATE();
    case 29:
      if (lookahead == 'F') ADVANCE(16);
      END_STATE();
    case 30:
      if (lookahead == 'L') ADVANCE(44);
      END_STATE();
    case 31:
      if (lookahead == 'M') ADVANCE(32);
      END_STATE();
    case 32:
      if (lookahead == 'M') ADVANCE(15);
      END_STATE();
    case 33:
      if (lookahead == 'M') ADVANCE(17);
      END_STATE();
    case 34:
      if (lookahead == 'M') ADVANCE(18);
      END_STATE();
    case 35:
      if (lookahead == 'M') ADVANCE(33);
      END_STATE();
    case 36:
      if (lookahead == 'M') ADVANCE(34);
      END_STATE();
    case 37:
      if (lookahead == 'N') ADVANCE(21);
      END_STATE();
    case 38:
      if (lookahead == 'N') ADVANCE(22);
      END_STATE();
    case 39:
      if (lookahead == 'N') ADVANCE(23);
      END_STATE();
    case 40:
      if (lookahead == 'O') ADVANCE(31);
      END_STATE();
    case 41:
      if (lookahead == 'O') ADVANCE(35);
      END_STATE();
    case 42:
      if (lookahead == 'O') ADVANCE(36);
      END_STATE();
    case 43:
      if (lookahead == 'P') ADVANCE(24);
      END_STATE();
    case 44:
      if (lookahead == 'T') ADVANCE(80);
      END_STATE();
    case 45:
      if (lookahead == 'T') ADVANCE(28);
      END_STATE();
    case 46:
      if (lookahead == 'U') ADVANCE(30);
      END_STATE();
    case 47:
      if (lookahead == 'U') ADVANCE(27);
      END_STATE();
    case 48:
      if (lookahead == 'U') ADVANCE(26);
      END_STATE();
    case 49:
      if (lookahead == '\\') SKIP(11);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(162);
      END_STATE();
    case 50:
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '@' &&
          lookahead != 0x20ac) ADVANCE(134);
      END_STATE();
    case 51:
      if (lookahead == '_') ADVANCE(19);
      END_STATE();
    case 52:
      if (lookahead == '_') ADVANCE(20);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 55:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 56:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(55);
      END_STATE();
    case 57:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 74,
        '\r', 1,
        '#', 73,
        '*', 78,
        '+', 137,
        ',', 136,
        '-', 138,
        ';', 88,
        '=', 139,
        '>', 89,
      );
      if (lookahead == '\\') SKIP(67);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 58:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(86);
      END_STATE();
    case 59:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == '\\') SKIP(69);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 60:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 74,
        '\r', 1,
        '#', 72,
        '*', 78,
        '/', 54,
        '<', 87,
        '>', 12,
        '@', 76,
        'C', 123,
        'D', 108,
        'Q', 130,
        'U', 126,
        '\\', 92,
        0x20ac, 79,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(134);
      END_STATE();
    case 61:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 74,
        '\r', 149,
        '#', 73,
        '*', 78,
        '+', 137,
        '-', 138,
        ':', 77,
        '=', 139,
        '\\', 150,
        '\t', 144,
        ' ', 144,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 62:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 74,
        '\r', 149,
        '#', 73,
        '*', 78,
        '+', 137,
        '-', 138,
        '=', 139,
        '\\', 152,
        '\t', 145,
        ' ', 145,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 63:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == ',') ADVANCE(136);
      if (lookahead == '\\') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(146);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 64:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == ',') ADVANCE(136);
      if (lookahead == '\\') ADVANCE(156);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 65:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(158);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(148);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 66:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(57);
      END_STATE();
    case 67:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(57);
      if (lookahead == '\r') SKIP(66);
      END_STATE();
    case 68:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(59);
      END_STATE();
    case 69:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(59);
      if (lookahead == '\r') SKIP(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(72);
      if (lookahead == '\\') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_u20ac);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_DEFAULT);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_COMMAND);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_UPDATE_COMMAND);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_QUEUE_COMMAND);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_command_arg);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\r') SKIP(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_command_arg);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(13);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_group_override_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '\r') ADVANCE(93);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\n') SKIP(50);
      if (lookahead == '\r') ADVANCE(95);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\n') SKIP(50);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\r') ADVANCE(135);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(128);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(120);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(129);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(121);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(122);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'C') ADVANCE(124);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'C') ADVANCE(125);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'D') ADVANCE(81);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'D') ADVANCE(83);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'D') ADVANCE(82);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'D') ADVANCE(97);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'E') ADVANCE(112);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'E') ADVANCE(132);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'E') ADVANCE(131);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'E') ADVANCE(133);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'F') ADVANCE(99);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'L') ADVANCE(127);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(115);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(98);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(100);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(101);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(116);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(117);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'N') ADVANCE(104);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'N') ADVANCE(105);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'N') ADVANCE(106);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'O') ADVANCE(114);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'O') ADVANCE(118);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'O') ADVANCE(119);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'P') ADVANCE(107);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'T') ADVANCE(80);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'T') ADVANCE(111);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'U') ADVANCE(113);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'U') ADVANCE(110);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'U') ADVANCE(109);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead == '_') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead != 0) ADVANCE(134);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_arg_name_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(160);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_additional_config);
      ADVANCE_MAP(
        '\n', 74,
        '\r', 149,
        '#', 73,
        '*', 78,
        '+', 137,
        '-', 138,
        ':', 77,
        '=', 139,
        '\\', 150,
        '\t', 144,
        ' ', 144,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_additional_config);
      ADVANCE_MAP(
        '\n', 74,
        '\r', 149,
        '#', 73,
        '*', 78,
        '+', 137,
        '-', 138,
        '=', 139,
        '\\', 152,
        '\t', 145,
        ' ', 145,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == ',') ADVANCE(136);
      if (lookahead == '\\') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(146);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == ',') ADVANCE(136);
      if (lookahead == '\\') ADVANCE(156);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(158);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(148);
      if (lookahead != 0) ADVANCE(161);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\r') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '\r') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(5);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(6);
      if (lookahead == '\r') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(6);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\r') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(7);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '\r') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_additional_config);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(161);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_effect_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(162);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 60},
  [2] = {.lex_state = 60},
  [3] = {.lex_state = 60},
  [4] = {.lex_state = 60},
  [5] = {.lex_state = 61},
  [6] = {.lex_state = 61},
  [7] = {.lex_state = 60},
  [8] = {.lex_state = 60},
  [9] = {.lex_state = 60},
  [10] = {.lex_state = 62},
  [11] = {.lex_state = 61},
  [12] = {.lex_state = 62},
  [13] = {.lex_state = 61},
  [14] = {.lex_state = 62},
  [15] = {.lex_state = 62},
  [16] = {.lex_state = 57},
  [17] = {.lex_state = 61},
  [18] = {.lex_state = 57},
  [19] = {.lex_state = 57},
  [20] = {.lex_state = 62},
  [21] = {.lex_state = 61},
  [22] = {.lex_state = 57},
  [23] = {.lex_state = 57},
  [24] = {.lex_state = 62},
  [25] = {.lex_state = 57},
  [26] = {.lex_state = 57},
  [27] = {.lex_state = 57},
  [28] = {.lex_state = 63},
  [29] = {.lex_state = 57},
  [30] = {.lex_state = 63},
  [31] = {.lex_state = 63},
  [32] = {.lex_state = 63},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 59},
  [36] = {.lex_state = 57},
  [37] = {.lex_state = 57},
  [38] = {.lex_state = 59},
  [39] = {.lex_state = 64},
  [40] = {.lex_state = 64},
  [41] = {.lex_state = 64},
  [42] = {.lex_state = 57},
  [43] = {.lex_state = 63},
  [44] = {.lex_state = 63},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 58},
  [47] = {.lex_state = 58},
  [48] = {.lex_state = 64},
  [49] = {.lex_state = 57},
  [50] = {.lex_state = 64},
  [51] = {.lex_state = 58},
  [52] = {.lex_state = 57},
  [53] = {.lex_state = 57},
  [54] = {.lex_state = 58},
  [55] = {.lex_state = 64},
  [56] = {.lex_state = 64},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 64},
  [59] = {.lex_state = 58},
  [60] = {.lex_state = 64},
  [61] = {.lex_state = 57},
  [62] = {.lex_state = 64},
  [63] = {.lex_state = 64},
  [64] = {.lex_state = 57},
  [65] = {.lex_state = 65},
  [66] = {.lex_state = 65},
  [67] = {.lex_state = 59},
  [68] = {.lex_state = 64},
  [69] = {.lex_state = 64},
  [70] = {.lex_state = 64},
  [71] = {.lex_state = 65},
  [72] = {.lex_state = 64},
  [73] = {.lex_state = 64},
  [74] = {.lex_state = 65},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 65},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 59},
  [82] = {.lex_state = 65},
  [83] = {.lex_state = 65},
  [84] = {.lex_state = 65},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 59},
  [92] = {.lex_state = 59},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 59},
  [95] = {.lex_state = 59},
  [96] = {.lex_state = 57},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 59},
  [99] = {.lex_state = 59},
  [100] = {.lex_state = 57},
  [101] = {.lex_state = 59},
  [102] = {.lex_state = 59},
  [103] = {.lex_state = 59},
  [104] = {.lex_state = 59},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 57},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 49},
  [115] = {.lex_state = 50},
  [116] = {.lex_state = 50},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 50},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_GT_GT_GT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_u20ac] = ACTIONS(1),
    [anon_sym_DEFAULT] = ACTIONS(1),
    [anon_sym_COMMAND] = ACTIONS(1),
    [anon_sym_UPDATE_COMMAND] = ACTIONS(1),
    [anon_sym_QUEUE_COMMAND] = ACTIONS(1),
    [sym_address] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(108),
    [sym__line] = STATE(3),
    [sym__statement] = STATE(80),
    [sym_group_filter] = STATE(80),
    [sym_synth_header] = STATE(80),
    [sym_selected] = STATE(125),
    [sym_effect_definition] = STATE(80),
    [sym_default_statement] = STATE(80),
    [sym_command] = STATE(80),
    [sym_command_type] = STATE(110),
    [sym_track] = STATE(80),
    [sym_track_metadata] = STATE(116),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [anon_sym_GT_GT_GT] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_u20ac] = ACTIONS(15),
    [anon_sym_DEFAULT] = ACTIONS(17),
    [anon_sym_COMMAND] = ACTIONS(19),
    [anon_sym_UPDATE_COMMAND] = ACTIONS(19),
    [anon_sym_QUEUE_COMMAND] = ACTIONS(19),
    [sym_address] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [sym_shuttle_content] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(32), 1,
      sym__newline,
    ACTIONS(35), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(38), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_STAR,
    ACTIONS(44), 1,
      anon_sym_u20ac,
    ACTIONS(47), 1,
      anon_sym_DEFAULT,
    ACTIONS(53), 1,
      sym_address,
    ACTIONS(56), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      sym_shuttle_content,
    STATE(105), 1,
      sym_selected,
    STATE(110), 1,
      sym_command_type,
    STATE(116), 1,
      sym_track_metadata,
    STATE(2), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    ACTIONS(50), 3,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
    STATE(97), 7,
      sym__statement,
      sym_group_filter,
      sym_synth_header,
      sym_effect_definition,
      sym_default_statement,
      sym_command,
      sym_track,
  [61] = 17,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_u20ac,
    ACTIONS(17), 1,
      anon_sym_DEFAULT,
    ACTIONS(21), 1,
      sym_address,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      sym_shuttle_content,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym__newline,
    STATE(110), 1,
      sym_command_type,
    STATE(116), 1,
      sym_track_metadata,
    STATE(125), 1,
      sym_selected,
    STATE(2), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    ACTIONS(19), 3,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
    STATE(75), 7,
      sym__statement,
      sym_group_filter,
      sym_synth_header,
      sym_effect_definition,
      sym_default_statement,
      sym_command,
      sym_track,
  [122] = 15,
    ACTIONS(9), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_u20ac,
    ACTIONS(17), 1,
      anon_sym_DEFAULT,
    ACTIONS(21), 1,
      sym_address,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      sym_shuttle_content,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym__newline,
    ACTIONS(70), 1,
      anon_sym_AT,
    STATE(105), 1,
      sym_selected,
    STATE(110), 1,
      sym_command_type,
    STATE(116), 1,
      sym_track_metadata,
    ACTIONS(19), 3,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
    STATE(93), 7,
      sym__statement,
      sym_group_filter,
      sym_synth_header,
      sym_effect_definition,
      sym_default_statement,
      sym_command,
      sym_track,
  [176] = 11,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      anon_sym_COLON,
    ACTIONS(80), 1,
      aux_sym_arg_name_token1,
    ACTIONS(82), 1,
      sym_number,
    ACTIONS(84), 1,
      sym_additional_config,
    STATE(39), 1,
      sym_arg,
    STATE(45), 1,
      sym_arg_name,
    STATE(71), 1,
      sym_arg_list,
    STATE(119), 1,
      sym_operator,
    ACTIONS(74), 2,
      sym_comment,
      sym__newline,
    ACTIONS(78), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [214] = 11,
    ACTIONS(80), 1,
      aux_sym_arg_name_token1,
    ACTIONS(82), 1,
      sym_number,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 1,
      anon_sym_COLON,
    ACTIONS(92), 1,
      sym_additional_config,
    STATE(39), 1,
      sym_arg,
    STATE(45), 1,
      sym_arg_name,
    STATE(74), 1,
      sym_arg_list,
    STATE(119), 1,
      sym_operator,
    ACTIONS(88), 2,
      sym_comment,
      sym__newline,
    ACTIONS(78), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [252] = 2,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 13,
      sym_comment,
      sym__newline,
      anon_sym_GT_GT_GT,
      anon_sym_AT,
      anon_sym_STAR,
      anon_sym_u20ac,
      anon_sym_DEFAULT,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
      sym_address,
      anon_sym_LT,
      sym_shuttle_content,
  [271] = 2,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 13,
      sym_comment,
      sym__newline,
      anon_sym_GT_GT_GT,
      anon_sym_AT,
      anon_sym_STAR,
      anon_sym_u20ac,
      anon_sym_DEFAULT,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
      sym_address,
      anon_sym_LT,
      sym_shuttle_content,
  [290] = 2,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 13,
      sym_comment,
      sym__newline,
      anon_sym_GT_GT_GT,
      anon_sym_AT,
      anon_sym_STAR,
      anon_sym_u20ac,
      anon_sym_DEFAULT,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
      sym_address,
      anon_sym_LT,
      sym_shuttle_content,
  [309] = 10,
    ACTIONS(80), 1,
      aux_sym_arg_name_token1,
    ACTIONS(82), 1,
      sym_number,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 1,
      sym_additional_config,
    STATE(39), 1,
      sym_arg,
    STATE(45), 1,
      sym_arg_name,
    STATE(66), 1,
      sym_arg_list,
    STATE(119), 1,
      sym_operator,
    ACTIONS(108), 2,
      sym_comment,
      sym__newline,
    ACTIONS(78), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [344] = 10,
    ACTIONS(80), 1,
      aux_sym_arg_name_token1,
    ACTIONS(84), 1,
      sym_additional_config,
    ACTIONS(112), 1,
      anon_sym_COLON,
    ACTIONS(114), 1,
      sym_number,
    STATE(33), 1,
      sym_arg_name,
    STATE(60), 1,
      sym_arg,
    STATE(79), 1,
      sym_arg_list,
    STATE(124), 1,
      sym_operator,
    ACTIONS(74), 2,
      sym_comment,
      sym__newline,
    ACTIONS(78), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [379] = 10,
    ACTIONS(80), 1,
      aux_sym_arg_name_token1,
    ACTIONS(82), 1,
      sym_number,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      sym_additional_config,
    STATE(39), 1,
      sym_arg,
    STATE(45), 1,
      sym_arg_name,
    STATE(65), 1,
      sym_arg_list,
    STATE(119), 1,
      sym_operator,
    ACTIONS(118), 2,
      sym_comment,
      sym__newline,
    ACTIONS(78), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [414] = 10,
    ACTIONS(80), 1,
      aux_sym_arg_name_token1,
    ACTIONS(92), 1,
      sym_additional_config,
    ACTIONS(114), 1,
      sym_number,
    ACTIONS(122), 1,
      anon_sym_COLON,
    STATE(33), 1,
      sym_arg_name,
    STATE(60), 1,
      sym_arg,
    STATE(82), 1,
      sym_arg_list,
    STATE(124), 1,
      sym_operator,
    ACTIONS(88), 2,
      sym_comment,
      sym__newline,
    ACTIONS(78), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [449] = 9,
    ACTIONS(80), 1,
      aux_sym_arg_name_token1,
    ACTIONS(114), 1,
      sym_number,
    ACTIONS(120), 1,
      sym_additional_config,
    STATE(33), 1,
      sym_arg_name,
    STATE(60), 1,
      sym_arg,
    STATE(84), 1,
      sym_arg_list,
    STATE(124), 1,
      sym_operator,
    ACTIONS(118), 2,
      sym_comment,
      sym__newline,
    ACTIONS(78), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [481] = 9,
    ACTIONS(80), 1,
      aux_sym_arg_name_token1,
    ACTIONS(110), 1,
      sym_additional_config,
    ACTIONS(114), 1,
      sym_number,
    STATE(33), 1,
      sym_arg_name,
    STATE(60), 1,
      sym_arg,
    STATE(83), 1,
      sym_arg_list,
    STATE(124), 1,
      sym_operator,
    ACTIONS(108), 2,
      sym_comment,
      sym__newline,
    ACTIONS(78), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [513] = 8,
    ACTIONS(128), 1,
      aux_sym_arg_name_token1,
    ACTIONS(130), 1,
      sym_number,
    STATE(34), 1,
      sym_arg_name,
    STATE(42), 1,
      sym_arg,
    STATE(89), 1,
      sym_arg_list,
    STATE(109), 1,
      sym_operator,
    ACTIONS(124), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [543] = 2,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 10,
      sym_comment,
      sym__newline,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      aux_sym_arg_name_token1,
      sym_number,
      sym_additional_config,
  [559] = 7,
    ACTIONS(128), 1,
      aux_sym_arg_name_token1,
    ACTIONS(130), 1,
      sym_number,
    STATE(34), 1,
      sym_arg_name,
    STATE(42), 1,
      sym_arg,
    STATE(85), 1,
      sym_arg_list,
    STATE(109), 1,
      sym_operator,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [584] = 7,
    ACTIONS(128), 1,
      aux_sym_arg_name_token1,
    ACTIONS(130), 1,
      sym_number,
    STATE(34), 1,
      sym_arg_name,
    STATE(42), 1,
      sym_arg,
    STATE(109), 1,
      sym_operator,
    STATE(112), 1,
      sym_arg_list,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [609] = 2,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 9,
      sym_comment,
      sym__newline,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      aux_sym_arg_name_token1,
      sym_number,
      sym_additional_config,
  [624] = 1,
    ACTIONS(134), 10,
      sym_comment,
      sym__newline,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      aux_sym_arg_name_token1,
      sym_number,
      sym_additional_config,
  [637] = 6,
    ACTIONS(128), 1,
      aux_sym_arg_name_token1,
    ACTIONS(130), 1,
      sym_number,
    STATE(34), 1,
      sym_arg_name,
    STATE(61), 1,
      sym_arg,
    STATE(109), 1,
      sym_operator,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [659] = 6,
    ACTIONS(128), 1,
      aux_sym_arg_name_token1,
    ACTIONS(140), 1,
      sym_number,
    STATE(45), 1,
      sym_arg_name,
    STATE(48), 1,
      sym_arg,
    STATE(119), 1,
      sym_operator,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [681] = 1,
    ACTIONS(138), 9,
      sym_comment,
      sym__newline,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      aux_sym_arg_name_token1,
      sym_number,
      sym_additional_config,
  [693] = 6,
    ACTIONS(128), 1,
      aux_sym_arg_name_token1,
    ACTIONS(142), 1,
      sym_number,
    STATE(33), 1,
      sym_arg_name,
    STATE(72), 1,
      sym_arg,
    STATE(124), 1,
      sym_operator,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [715] = 3,
    ACTIONS(146), 1,
      aux_sym_arg_name_token1,
    STATE(53), 1,
      sym_ref,
    ACTIONS(144), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [729] = 3,
    ACTIONS(146), 1,
      aux_sym_arg_name_token1,
    STATE(64), 1,
      sym_ref,
    ACTIONS(148), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [743] = 4,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 1,
      aux_sym_arg_name_token1,
    STATE(55), 1,
      sym_ref,
    ACTIONS(150), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [759] = 3,
    ACTIONS(146), 1,
      aux_sym_arg_name_token1,
    STATE(49), 1,
      sym_ref,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [773] = 4,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 1,
      aux_sym_arg_name_token1,
    STATE(56), 1,
      sym_ref,
    ACTIONS(156), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [789] = 4,
    ACTIONS(152), 1,
      aux_sym_arg_name_token1,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    STATE(58), 1,
      sym_ref,
    ACTIONS(158), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [805] = 3,
    ACTIONS(160), 1,
      aux_sym_arg_name_token1,
    STATE(69), 1,
      sym_ref,
    ACTIONS(150), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [818] = 3,
    ACTIONS(162), 1,
      sym_number,
    STATE(126), 1,
      sym_operator,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [831] = 3,
    ACTIONS(164), 1,
      sym_number,
    STATE(113), 1,
      sym_operator,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [844] = 3,
    ACTIONS(168), 1,
      aux_sym_group_override_token1,
    STATE(35), 2,
      sym_group_name,
      aux_sym_group_filter_repeat1,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [857] = 3,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(171), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
  [870] = 3,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(175), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
  [883] = 3,
    ACTIONS(182), 1,
      aux_sym_group_override_token1,
    STATE(35), 2,
      sym_group_name,
      aux_sym_group_filter_repeat1,
    ACTIONS(180), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [896] = 4,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(186), 3,
      sym_comment,
      sym__newline,
      sym_additional_config,
  [911] = 4,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(190), 3,
      sym_comment,
      sym__newline,
      sym_additional_config,
  [926] = 4,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(192), 3,
      sym_comment,
      sym__newline,
      sym_additional_config,
  [941] = 3,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(184), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
  [954] = 3,
    ACTIONS(160), 1,
      aux_sym_arg_name_token1,
    STATE(70), 1,
      sym_ref,
    ACTIONS(156), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [967] = 3,
    ACTIONS(160), 1,
      aux_sym_arg_name_token1,
    STATE(73), 1,
      sym_ref,
    ACTIONS(158), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [980] = 3,
    ACTIONS(197), 1,
      sym_number,
    STATE(122), 1,
      sym_operator,
    ACTIONS(126), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [993] = 4,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    ACTIONS(203), 1,
      sym_command_arg,
    STATE(51), 1,
      aux_sym_command_repeat1,
    ACTIONS(201), 2,
      sym_comment,
      sym__newline,
  [1007] = 4,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 1,
      sym_command_arg,
    STATE(59), 1,
      aux_sym_command_repeat1,
    ACTIONS(201), 2,
      sym_comment,
      sym__newline,
  [1021] = 2,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    ACTIONS(192), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1031] = 1,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1039] = 2,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
    ACTIONS(211), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1049] = 4,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
    ACTIONS(217), 1,
      sym_command_arg,
    STATE(51), 1,
      aux_sym_command_repeat1,
    ACTIONS(215), 2,
      sym_comment,
      sym__newline,
  [1063] = 1,
    ACTIONS(209), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1071] = 1,
    ACTIONS(148), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1079] = 4,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
    ACTIONS(224), 1,
      sym_command_arg,
    STATE(46), 1,
      aux_sym_command_repeat1,
    ACTIONS(222), 2,
      sym_comment,
      sym__newline,
  [1093] = 2,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1103] = 2,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1113] = 1,
    ACTIONS(226), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      sym_number,
  [1121] = 2,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    ACTIONS(228), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1131] = 4,
    ACTIONS(203), 1,
      sym_command_arg,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      aux_sym_command_repeat1,
    ACTIONS(232), 2,
      sym_comment,
      sym__newline,
  [1145] = 3,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(63), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(186), 3,
      sym_comment,
      sym__newline,
      sym_additional_config,
  [1157] = 1,
    ACTIONS(175), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1165] = 3,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(192), 3,
      sym_comment,
      sym__newline,
      sym_additional_config,
  [1177] = 3,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(190), 3,
      sym_comment,
      sym__newline,
      sym_additional_config,
  [1189] = 1,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1197] = 3,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
    ACTIONS(243), 1,
      sym_additional_config,
    ACTIONS(241), 2,
      sym_comment,
      sym__newline,
  [1208] = 3,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      sym_additional_config,
    ACTIONS(118), 2,
      sym_comment,
      sym__newline,
  [1219] = 1,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
      aux_sym_group_override_token1,
  [1226] = 1,
    ACTIONS(211), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1233] = 1,
    ACTIONS(156), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1240] = 1,
    ACTIONS(158), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1247] = 3,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 1,
      sym_additional_config,
    ACTIONS(88), 2,
      sym_comment,
      sym__newline,
  [1258] = 1,
    ACTIONS(192), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1265] = 1,
    ACTIONS(228), 4,
      sym_comment,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1272] = 3,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 1,
      sym_additional_config,
    ACTIONS(108), 2,
      sym_comment,
      sym__newline,
  [1283] = 3,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym__newline,
  [1293] = 1,
    ACTIONS(239), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1299] = 1,
    ACTIONS(251), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1305] = 1,
    ACTIONS(253), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1311] = 2,
    ACTIONS(92), 1,
      sym_additional_config,
    ACTIONS(88), 2,
      sym_comment,
      sym__newline,
  [1319] = 3,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym__newline,
  [1329] = 2,
    ACTIONS(182), 1,
      aux_sym_group_override_token1,
    STATE(38), 2,
      sym_group_name,
      aux_sym_group_filter_repeat1,
  [1337] = 2,
    ACTIONS(110), 1,
      sym_additional_config,
    ACTIONS(108), 2,
      sym_comment,
      sym__newline,
  [1345] = 2,
    ACTIONS(120), 1,
      sym_additional_config,
    ACTIONS(118), 2,
      sym_comment,
      sym__newline,
  [1353] = 2,
    ACTIONS(243), 1,
      sym_additional_config,
    ACTIONS(241), 2,
      sym_comment,
      sym__newline,
  [1361] = 1,
    ACTIONS(255), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1367] = 1,
    ACTIONS(106), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1373] = 1,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1379] = 1,
    ACTIONS(116), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1385] = 1,
    ACTIONS(257), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1391] = 1,
    ACTIONS(259), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [1397] = 2,
    ACTIONS(261), 1,
      aux_sym_group_override_token1,
    STATE(6), 1,
      sym_instrument_name,
  [1404] = 2,
    ACTIONS(263), 1,
      aux_sym_group_override_token1,
    STATE(100), 1,
      sym_group_override,
  [1411] = 2,
    ACTIONS(265), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym__newline,
  [1418] = 2,
    ACTIONS(269), 1,
      aux_sym_group_override_token1,
    STATE(13), 1,
      sym_instrument_name,
  [1425] = 2,
    ACTIONS(271), 1,
      aux_sym_group_override_token1,
    STATE(121), 1,
      sym_effect_type,
  [1432] = 1,
    ACTIONS(273), 2,
      anon_sym_SEMI,
      anon_sym_GT,
  [1437] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym__newline,
  [1444] = 2,
    ACTIONS(261), 1,
      aux_sym_group_override_token1,
    STATE(5), 1,
      sym_instrument_name,
  [1451] = 2,
    ACTIONS(275), 1,
      aux_sym_group_override_token1,
    STATE(10), 1,
      sym_group_name,
  [1458] = 2,
    ACTIONS(277), 1,
      anon_sym_SEMI,
    ACTIONS(279), 1,
      anon_sym_GT,
  [1465] = 2,
    ACTIONS(275), 1,
      aux_sym_group_override_token1,
    STATE(12), 1,
      sym_group_name,
  [1472] = 2,
    ACTIONS(269), 1,
      aux_sym_group_override_token1,
    STATE(11), 1,
      sym_instrument_name,
  [1479] = 2,
    ACTIONS(281), 1,
      aux_sym_group_override_token1,
    STATE(15), 1,
      sym_group_name,
  [1486] = 2,
    ACTIONS(281), 1,
      aux_sym_group_override_token1,
    STATE(14), 1,
      sym_group_name,
  [1493] = 1,
    ACTIONS(283), 1,
      anon_sym_AT,
  [1497] = 1,
    ACTIONS(285), 1,
      anon_sym_AT,
  [1501] = 1,
    ACTIONS(287), 1,
      sym__newline,
  [1505] = 1,
    ACTIONS(289), 1,
      ts_builtin_sym_end,
  [1509] = 1,
    ACTIONS(164), 1,
      sym_number,
  [1513] = 1,
    ACTIONS(291), 1,
      sym_address,
  [1517] = 1,
    ACTIONS(267), 1,
      sym__newline,
  [1521] = 1,
    ACTIONS(293), 1,
      anon_sym_GT,
  [1525] = 1,
    ACTIONS(295), 1,
      sym_number,
  [1529] = 1,
    ACTIONS(297), 1,
      sym_effect_id,
  [1533] = 1,
    ACTIONS(299), 1,
      sym_shuttle_content,
  [1537] = 1,
    ACTIONS(301), 1,
      sym_shuttle_content,
  [1541] = 1,
    ACTIONS(303), 1,
      sym_address,
  [1545] = 1,
    ACTIONS(305), 1,
      sym_shuttle_content,
  [1549] = 1,
    ACTIONS(197), 1,
      sym_number,
  [1553] = 1,
    ACTIONS(307), 1,
      anon_sym_COLON,
  [1557] = 1,
    ACTIONS(309), 1,
      anon_sym_COLON,
  [1561] = 1,
    ACTIONS(311), 1,
      sym_number,
  [1565] = 1,
    ACTIONS(313), 1,
      sym_number,
  [1569] = 1,
    ACTIONS(162), 1,
      sym_number,
  [1573] = 1,
    ACTIONS(315), 1,
      anon_sym_AT,
  [1577] = 1,
    ACTIONS(317), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 122,
  [SMALL_STATE(5)] = 176,
  [SMALL_STATE(6)] = 214,
  [SMALL_STATE(7)] = 252,
  [SMALL_STATE(8)] = 271,
  [SMALL_STATE(9)] = 290,
  [SMALL_STATE(10)] = 309,
  [SMALL_STATE(11)] = 344,
  [SMALL_STATE(12)] = 379,
  [SMALL_STATE(13)] = 414,
  [SMALL_STATE(14)] = 449,
  [SMALL_STATE(15)] = 481,
  [SMALL_STATE(16)] = 513,
  [SMALL_STATE(17)] = 543,
  [SMALL_STATE(18)] = 559,
  [SMALL_STATE(19)] = 584,
  [SMALL_STATE(20)] = 609,
  [SMALL_STATE(21)] = 624,
  [SMALL_STATE(22)] = 637,
  [SMALL_STATE(23)] = 659,
  [SMALL_STATE(24)] = 681,
  [SMALL_STATE(25)] = 693,
  [SMALL_STATE(26)] = 715,
  [SMALL_STATE(27)] = 729,
  [SMALL_STATE(28)] = 743,
  [SMALL_STATE(29)] = 759,
  [SMALL_STATE(30)] = 773,
  [SMALL_STATE(31)] = 789,
  [SMALL_STATE(32)] = 805,
  [SMALL_STATE(33)] = 818,
  [SMALL_STATE(34)] = 831,
  [SMALL_STATE(35)] = 844,
  [SMALL_STATE(36)] = 857,
  [SMALL_STATE(37)] = 870,
  [SMALL_STATE(38)] = 883,
  [SMALL_STATE(39)] = 896,
  [SMALL_STATE(40)] = 911,
  [SMALL_STATE(41)] = 926,
  [SMALL_STATE(42)] = 941,
  [SMALL_STATE(43)] = 954,
  [SMALL_STATE(44)] = 967,
  [SMALL_STATE(45)] = 980,
  [SMALL_STATE(46)] = 993,
  [SMALL_STATE(47)] = 1007,
  [SMALL_STATE(48)] = 1021,
  [SMALL_STATE(49)] = 1031,
  [SMALL_STATE(50)] = 1039,
  [SMALL_STATE(51)] = 1049,
  [SMALL_STATE(52)] = 1063,
  [SMALL_STATE(53)] = 1071,
  [SMALL_STATE(54)] = 1079,
  [SMALL_STATE(55)] = 1093,
  [SMALL_STATE(56)] = 1103,
  [SMALL_STATE(57)] = 1113,
  [SMALL_STATE(58)] = 1121,
  [SMALL_STATE(59)] = 1131,
  [SMALL_STATE(60)] = 1145,
  [SMALL_STATE(61)] = 1157,
  [SMALL_STATE(62)] = 1165,
  [SMALL_STATE(63)] = 1177,
  [SMALL_STATE(64)] = 1189,
  [SMALL_STATE(65)] = 1197,
  [SMALL_STATE(66)] = 1208,
  [SMALL_STATE(67)] = 1219,
  [SMALL_STATE(68)] = 1226,
  [SMALL_STATE(69)] = 1233,
  [SMALL_STATE(70)] = 1240,
  [SMALL_STATE(71)] = 1247,
  [SMALL_STATE(72)] = 1258,
  [SMALL_STATE(73)] = 1265,
  [SMALL_STATE(74)] = 1272,
  [SMALL_STATE(75)] = 1283,
  [SMALL_STATE(76)] = 1293,
  [SMALL_STATE(77)] = 1299,
  [SMALL_STATE(78)] = 1305,
  [SMALL_STATE(79)] = 1311,
  [SMALL_STATE(80)] = 1319,
  [SMALL_STATE(81)] = 1329,
  [SMALL_STATE(82)] = 1337,
  [SMALL_STATE(83)] = 1345,
  [SMALL_STATE(84)] = 1353,
  [SMALL_STATE(85)] = 1361,
  [SMALL_STATE(86)] = 1367,
  [SMALL_STATE(87)] = 1373,
  [SMALL_STATE(88)] = 1379,
  [SMALL_STATE(89)] = 1385,
  [SMALL_STATE(90)] = 1391,
  [SMALL_STATE(91)] = 1397,
  [SMALL_STATE(92)] = 1404,
  [SMALL_STATE(93)] = 1411,
  [SMALL_STATE(94)] = 1418,
  [SMALL_STATE(95)] = 1425,
  [SMALL_STATE(96)] = 1432,
  [SMALL_STATE(97)] = 1437,
  [SMALL_STATE(98)] = 1444,
  [SMALL_STATE(99)] = 1451,
  [SMALL_STATE(100)] = 1458,
  [SMALL_STATE(101)] = 1465,
  [SMALL_STATE(102)] = 1472,
  [SMALL_STATE(103)] = 1479,
  [SMALL_STATE(104)] = 1486,
  [SMALL_STATE(105)] = 1493,
  [SMALL_STATE(106)] = 1497,
  [SMALL_STATE(107)] = 1501,
  [SMALL_STATE(108)] = 1505,
  [SMALL_STATE(109)] = 1509,
  [SMALL_STATE(110)] = 1513,
  [SMALL_STATE(111)] = 1517,
  [SMALL_STATE(112)] = 1521,
  [SMALL_STATE(113)] = 1525,
  [SMALL_STATE(114)] = 1529,
  [SMALL_STATE(115)] = 1533,
  [SMALL_STATE(116)] = 1537,
  [SMALL_STATE(117)] = 1541,
  [SMALL_STATE(118)] = 1545,
  [SMALL_STATE(119)] = 1549,
  [SMALL_STATE(120)] = 1553,
  [SMALL_STATE(121)] = 1557,
  [SMALL_STATE(122)] = 1561,
  [SMALL_STATE(123)] = 1565,
  [SMALL_STATE(124)] = 1569,
  [SMALL_STATE(125)] = 1573,
  [SMALL_STATE(126)] = 1577,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 4, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_definition, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instrument_name, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instrument_name, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_name, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_name, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_filter_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_filter_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_filter, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [194] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 4, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 0),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_name, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 4, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [236] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 6, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 6, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 7, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_statement, 2, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_definition, 5, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track, 2, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_override, 1, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selected, 1, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [289] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track_metadata, 3, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_type, 1, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track_metadata, 5, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_type, 1, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jdw_billboarding(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jdw_billboarding",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
