/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 121
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym__newline = 2,
  anon_sym_GT_GT_GT = 3,
  anon_sym_AT = 4,
  anon_sym_COLON = 5,
  anon_sym_STAR = 6,
  anon_sym_u20ac = 7,
  anon_sym_DEFAULT = 8,
  anon_sym_COMMAND = 9,
  anon_sym_UPDATE_COMMAND = 10,
  anon_sym_QUEUE_COMMAND = 11,
  sym_address = 12,
  sym_command_arg = 13,
  anon_sym_LT = 14,
  anon_sym_SEMI = 15,
  anon_sym_GT = 16,
  aux_sym_group_override_token1 = 17,
  sym_shuttle_content = 18,
  anon_sym_COMMA = 19,
  anon_sym_PLUS = 20,
  anon_sym_DASH = 21,
  anon_sym_EQ = 22,
  aux_sym_arg_name_token1 = 23,
  sym_number = 24,
  sym_additional_config = 25,
  sym_effect_id = 26,
  sym_source_file = 27,
  sym__line = 28,
  sym__statement = 29,
  sym_group_filter = 30,
  sym_synth_header = 31,
  sym_selected = 32,
  sym_effect_definition = 33,
  sym_default_statement = 34,
  sym_command = 35,
  sym_command_type = 36,
  sym_track = 37,
  sym_track_metadata = 38,
  sym_group_override = 39,
  sym_arg_list = 40,
  sym_arg = 41,
  sym_operator = 42,
  sym_arg_name = 43,
  sym_ref = 44,
  sym_instrument_name = 45,
  sym_group_name = 46,
  sym_effect_type = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_group_filter_repeat1 = 49,
  aux_sym_command_repeat1 = 50,
  aux_sym_arg_list_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [anon_sym_GT_GT_GT] = ">>>",
  [anon_sym_AT] = "@",
  [anon_sym_COLON] = ":",
  [anon_sym_STAR] = "*",
  [anon_sym_u20ac] = "\u20ac",
  [anon_sym_DEFAULT] = "DEFAULT",
  [anon_sym_COMMAND] = "COMMAND",
  [anon_sym_UPDATE_COMMAND] = "UPDATE_COMMAND",
  [anon_sym_QUEUE_COMMAND] = "QUEUE_COMMAND",
  [sym_address] = "address",
  [sym_command_arg] = "command_arg",
  [anon_sym_LT] = "<",
  [anon_sym_SEMI] = ";",
  [anon_sym_GT] = ">",
  [aux_sym_group_override_token1] = "group_override_token1",
  [sym_shuttle_content] = "shuttle_content",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ] = "=",
  [aux_sym_arg_name_token1] = "arg_name_token1",
  [sym_number] = "number",
  [sym_additional_config] = "additional_config",
  [sym_effect_id] = "effect_id",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_group_filter] = "group_filter",
  [sym_synth_header] = "synth_header",
  [sym_selected] = "selected",
  [sym_effect_definition] = "effect_definition",
  [sym_default_statement] = "default_statement",
  [sym_command] = "command",
  [sym_command_type] = "command_type",
  [sym_track] = "track",
  [sym_track_metadata] = "track_metadata",
  [sym_group_override] = "group_override",
  [sym_arg_list] = "arg_list",
  [sym_arg] = "arg",
  [sym_operator] = "operator",
  [sym_arg_name] = "arg_name",
  [sym_ref] = "ref",
  [sym_instrument_name] = "instrument_name",
  [sym_group_name] = "group_name",
  [sym_effect_type] = "effect_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_group_filter_repeat1] = "group_filter_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [anon_sym_GT_GT_GT] = anon_sym_GT_GT_GT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_u20ac] = anon_sym_u20ac,
  [anon_sym_DEFAULT] = anon_sym_DEFAULT,
  [anon_sym_COMMAND] = anon_sym_COMMAND,
  [anon_sym_UPDATE_COMMAND] = anon_sym_UPDATE_COMMAND,
  [anon_sym_QUEUE_COMMAND] = anon_sym_QUEUE_COMMAND,
  [sym_address] = sym_address,
  [sym_command_arg] = sym_command_arg,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_group_override_token1] = aux_sym_group_override_token1,
  [sym_shuttle_content] = sym_shuttle_content,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_arg_name_token1] = aux_sym_arg_name_token1,
  [sym_number] = sym_number,
  [sym_additional_config] = sym_additional_config,
  [sym_effect_id] = sym_effect_id,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_group_filter] = sym_group_filter,
  [sym_synth_header] = sym_synth_header,
  [sym_selected] = sym_selected,
  [sym_effect_definition] = sym_effect_definition,
  [sym_default_statement] = sym_default_statement,
  [sym_command] = sym_command,
  [sym_command_type] = sym_command_type,
  [sym_track] = sym_track,
  [sym_track_metadata] = sym_track_metadata,
  [sym_group_override] = sym_group_override,
  [sym_arg_list] = sym_arg_list,
  [sym_arg] = sym_arg,
  [sym_operator] = sym_operator,
  [sym_arg_name] = sym_arg_name,
  [sym_ref] = sym_ref,
  [sym_instrument_name] = sym_instrument_name,
  [sym_group_name] = sym_group_name,
  [sym_effect_type] = sym_effect_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_group_filter_repeat1] = aux_sym_group_filter_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u20ac] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DEFAULT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMAND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UPDATE_COMMAND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QUEUE_COMMAND] = {
    .visible = true,
    .named = false,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [sym_command_arg] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_group_override_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_shuttle_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_arg_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_additional_config] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_id] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_group_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_synth_header] = {
    .visible = true,
    .named = true,
  },
  [sym_selected] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_default_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_command_type] = {
    .visible = true,
    .named = true,
  },
  [sym_track] = {
    .visible = true,
    .named = true,
  },
  [sym_track_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_group_override] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_name] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_instrument_name] = {
    .visible = true,
    .named = true,
  },
  [sym_group_name] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_filter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 4,
  [10] = 5,
  [11] = 11,
  [12] = 7,
  [13] = 8,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 14,
  [21] = 17,
  [22] = 19,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 23,
  [27] = 27,
  [28] = 27,
  [29] = 24,
  [30] = 25,
  [31] = 24,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 35,
  [39] = 32,
  [40] = 34,
  [41] = 25,
  [42] = 23,
  [43] = 27,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 45,
  [49] = 46,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 47,
  [54] = 34,
  [55] = 55,
  [56] = 35,
  [57] = 44,
  [58] = 32,
  [59] = 50,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 19,
  [67] = 67,
  [68] = 47,
  [69] = 44,
  [70] = 46,
  [71] = 45,
  [72] = 50,
  [73] = 73,
  [74] = 74,
  [75] = 65,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 74,
  [82] = 63,
  [83] = 62,
  [84] = 64,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 85,
  [96] = 96,
  [97] = 76,
  [98] = 91,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 107,
  [114] = 114,
  [115] = 115,
  [116] = 100,
  [117] = 112,
  [118] = 107,
  [119] = 119,
  [120] = 100,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 72,
        '\r', 1,
        '#', 71,
        '*', 76,
        '+', 135,
        ',', 134,
        '-', 136,
        '/', 54,
        ':', 75,
        ';', 86,
        '<', 85,
        '=', 137,
        '>', 88,
        '@', 74,
        'C', 42,
        'D', 27,
        'Q', 49,
        'U', 45,
      );
      if (lookahead == '\\') SKIP(56);
      if (lookahead == 0x20ac) ADVANCE(77);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(139);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(72);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 72,
        '\r', 1,
        '#', 71,
        '*', 76,
        '/', 54,
        '<', 85,
        '>', 14,
        '@', 74,
        'C', 121,
        'D', 106,
        'Q', 128,
        'U', 124,
        '\\', 90,
        0x20ac, 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(132);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(83);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(84);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 72,
        '\r', 147,
        '#', 71,
        '*', 76,
        '+', 135,
        '-', 136,
        ':', 75,
        '=', 137,
        '\\', 148,
        '\t', 142,
        ' ', 142,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 72,
        '\r', 147,
        '#', 71,
        '*', 76,
        '+', 135,
        '-', 136,
        '=', 137,
        '\\', 150,
        '\t', 143,
        ' ', 143,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == ',') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(152);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == ',') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(145);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(156);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(146);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(3);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(12);
      END_STATE();
    case 11:
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '\r') SKIP(10);
      END_STATE();
    case 12:
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '\\') SKIP(11);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(160);
      END_STATE();
    case 13:
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '@' &&
          lookahead != 0x20ac) ADVANCE(132);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(73);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(47);
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead == 'A') ADVANCE(48);
      END_STATE();
    case 19:
      if (lookahead == 'A') ADVANCE(40);
      END_STATE();
    case 20:
      if (lookahead == 'A') ADVANCE(41);
      END_STATE();
    case 21:
      if (lookahead == 'C') ADVANCE(43);
      END_STATE();
    case 22:
      if (lookahead == 'C') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == 'D') ADVANCE(79);
      END_STATE();
    case 24:
      if (lookahead == 'D') ADVANCE(81);
      END_STATE();
    case 25:
      if (lookahead == 'D') ADVANCE(80);
      END_STATE();
    case 26:
      if (lookahead == 'D') ADVANCE(16);
      END_STATE();
    case 27:
      if (lookahead == 'E') ADVANCE(31);
      END_STATE();
    case 28:
      if (lookahead == 'E') ADVANCE(51);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == 'E') ADVANCE(52);
      END_STATE();
    case 31:
      if (lookahead == 'F') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 'L') ADVANCE(46);
      END_STATE();
    case 33:
      if (lookahead == 'M') ADVANCE(34);
      END_STATE();
    case 34:
      if (lookahead == 'M') ADVANCE(17);
      END_STATE();
    case 35:
      if (lookahead == 'M') ADVANCE(19);
      END_STATE();
    case 36:
      if (lookahead == 'M') ADVANCE(20);
      END_STATE();
    case 37:
      if (lookahead == 'M') ADVANCE(35);
      END_STATE();
    case 38:
      if (lookahead == 'M') ADVANCE(36);
      END_STATE();
    case 39:
      if (lookahead == 'N') ADVANCE(23);
      END_STATE();
    case 40:
      if (lookahead == 'N') ADVANCE(24);
      END_STATE();
    case 41:
      if (lookahead == 'N') ADVANCE(25);
      END_STATE();
    case 42:
      if (lookahead == 'O') ADVANCE(33);
      END_STATE();
    case 43:
      if (lookahead == 'O') ADVANCE(37);
      END_STATE();
    case 44:
      if (lookahead == 'O') ADVANCE(38);
      END_STATE();
    case 45:
      if (lookahead == 'P') ADVANCE(26);
      END_STATE();
    case 46:
      if (lookahead == 'T') ADVANCE(78);
      END_STATE();
    case 47:
      if (lookahead == 'T') ADVANCE(30);
      END_STATE();
    case 48:
      if (lookahead == 'U') ADVANCE(32);
      END_STATE();
    case 49:
      if (lookahead == 'U') ADVANCE(29);
      END_STATE();
    case 50:
      if (lookahead == 'U') ADVANCE(28);
      END_STATE();
    case 51:
      if (lookahead == '_') ADVANCE(21);
      END_STATE();
    case 52:
      if (lookahead == '_') ADVANCE(22);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 55:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 56:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(55);
      END_STATE();
    case 57:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 72,
        '\r', 1,
        '#', 71,
        '*', 76,
        '+', 135,
        ',', 134,
        '-', 136,
        ';', 86,
        '=', 137,
        '>', 87,
      );
      if (lookahead == '\\') SKIP(67);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(139);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      END_STATE();
    case 58:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 72,
        '\r', 1,
        '#', 71,
        '*', 76,
        '/', 54,
        '<', 85,
        '>', 14,
        '@', 74,
        'C', 121,
        'D', 106,
        'Q', 128,
        'U', 124,
        '\\', 90,
        0x20ac, 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(132);
      END_STATE();
    case 59:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(83);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(84);
      END_STATE();
    case 60:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '\\') SKIP(69);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 61:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 72,
        '\r', 147,
        '#', 71,
        '*', 76,
        '+', 135,
        '-', 136,
        ':', 75,
        '=', 137,
        '\\', 148,
        '\t', 142,
        ' ', 142,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 62:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 72,
        '\r', 147,
        '#', 71,
        '*', 76,
        '+', 135,
        '-', 136,
        '=', 137,
        '\\', 150,
        '\t', 143,
        ' ', 143,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 63:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == ',') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(152);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 64:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == ',') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(145);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 65:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(156);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(146);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 66:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(57);
      END_STATE();
    case 67:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(57);
      if (lookahead == '\r') SKIP(66);
      END_STATE();
    case 68:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(60);
      END_STATE();
    case 69:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') SKIP(60);
      if (lookahead == '\r') SKIP(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_u20ac);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_DEFAULT);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_COMMAND);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_UPDATE_COMMAND);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_QUEUE_COMMAND);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_address);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_command_arg);
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '\r') SKIP(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_command_arg);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_group_override_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\r') ADVANCE(91);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\r') ADVANCE(93);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\r') ADVANCE(133);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(126);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(118);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(127);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(119);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'A') ADVANCE(120);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'C') ADVANCE(122);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'C') ADVANCE(123);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'D') ADVANCE(79);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'D') ADVANCE(81);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'D') ADVANCE(80);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'D') ADVANCE(95);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'E') ADVANCE(110);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'E') ADVANCE(130);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'E') ADVANCE(129);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'E') ADVANCE(131);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'F') ADVANCE(97);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'L') ADVANCE(125);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(113);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(96);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(98);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(99);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(114);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'M') ADVANCE(115);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'N') ADVANCE(102);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'N') ADVANCE(103);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'N') ADVANCE(104);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'O') ADVANCE(112);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'O') ADVANCE(116);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'O') ADVANCE(117);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'P') ADVANCE(105);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'T') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'T') ADVANCE(109);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'U') ADVANCE(111);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'U') ADVANCE(108);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == 'U') ADVANCE(107);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead == '_') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead == '_') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_shuttle_content);
      if (lookahead == '\\') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(132);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_arg_name_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(139);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(158);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_additional_config);
      ADVANCE_MAP(
        '\n', 72,
        '\r', 147,
        '#', 71,
        '*', 76,
        '+', 135,
        '-', 136,
        ':', 75,
        '=', 137,
        '\\', 148,
        '\t', 142,
        ' ', 142,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_additional_config);
      ADVANCE_MAP(
        '\n', 72,
        '\r', 147,
        '#', 71,
        '*', 76,
        '+', 135,
        '-', 136,
        '=', 137,
        '\\', 150,
        '\t', 143,
        ' ', 143,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == ',') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(152);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == ',') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(154);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(145);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(147);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(156);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(146);
      if (lookahead != 0) ADVANCE(159);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\r') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '\r') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(5);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(6);
      if (lookahead == '\r') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(6);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\r') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(7);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '\r') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead == '\n') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_additional_config);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_additional_config);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(159);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_effect_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(160);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 58},
  [2] = {.lex_state = 58},
  [3] = {.lex_state = 58},
  [4] = {.lex_state = 61},
  [5] = {.lex_state = 61},
  [6] = {.lex_state = 58},
  [7] = {.lex_state = 62},
  [8] = {.lex_state = 62},
  [9] = {.lex_state = 61},
  [10] = {.lex_state = 61},
  [11] = {.lex_state = 57},
  [12] = {.lex_state = 62},
  [13] = {.lex_state = 62},
  [14] = {.lex_state = 61},
  [15] = {.lex_state = 57},
  [16] = {.lex_state = 57},
  [17] = {.lex_state = 57},
  [18] = {.lex_state = 57},
  [19] = {.lex_state = 62},
  [20] = {.lex_state = 61},
  [21] = {.lex_state = 57},
  [22] = {.lex_state = 62},
  [23] = {.lex_state = 63},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 63},
  [26] = {.lex_state = 57},
  [27] = {.lex_state = 63},
  [28] = {.lex_state = 57},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 57},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 57},
  [33] = {.lex_state = 60},
  [34] = {.lex_state = 64},
  [35] = {.lex_state = 64},
  [36] = {.lex_state = 60},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 57},
  [39] = {.lex_state = 64},
  [40] = {.lex_state = 57},
  [41] = {.lex_state = 63},
  [42] = {.lex_state = 63},
  [43] = {.lex_state = 63},
  [44] = {.lex_state = 64},
  [45] = {.lex_state = 57},
  [46] = {.lex_state = 64},
  [47] = {.lex_state = 57},
  [48] = {.lex_state = 64},
  [49] = {.lex_state = 57},
  [50] = {.lex_state = 64},
  [51] = {.lex_state = 59},
  [52] = {.lex_state = 59},
  [53] = {.lex_state = 64},
  [54] = {.lex_state = 64},
  [55] = {.lex_state = 59},
  [56] = {.lex_state = 64},
  [57] = {.lex_state = 57},
  [58] = {.lex_state = 64},
  [59] = {.lex_state = 57},
  [60] = {.lex_state = 59},
  [61] = {.lex_state = 59},
  [62] = {.lex_state = 65},
  [63] = {.lex_state = 65},
  [64] = {.lex_state = 65},
  [65] = {.lex_state = 65},
  [66] = {.lex_state = 60},
  [67] = {.lex_state = 60},
  [68] = {.lex_state = 64},
  [69] = {.lex_state = 64},
  [70] = {.lex_state = 64},
  [71] = {.lex_state = 64},
  [72] = {.lex_state = 64},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 60},
  [75] = {.lex_state = 65},
  [76] = {.lex_state = 60},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 57},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 60},
  [81] = {.lex_state = 60},
  [82] = {.lex_state = 65},
  [83] = {.lex_state = 65},
  [84] = {.lex_state = 65},
  [85] = {.lex_state = 60},
  [86] = {.lex_state = 60},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 60},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 60},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 60},
  [98] = {.lex_state = 60},
  [99] = {.lex_state = 57},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 13},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 57},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 13},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 13},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 12},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
    [anon_sym_GT_GT_GT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_u20ac] = ACTIONS(1),
    [anon_sym_DEFAULT] = ACTIONS(1),
    [anon_sym_COMMAND] = ACTIONS(1),
    [anon_sym_UPDATE_COMMAND] = ACTIONS(1),
    [anon_sym_QUEUE_COMMAND] = ACTIONS(1),
    [sym_address] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(109),
    [sym__line] = STATE(3),
    [sym__statement] = STATE(96),
    [sym_group_filter] = STATE(96),
    [sym_synth_header] = STATE(96),
    [sym_selected] = STATE(117),
    [sym_effect_definition] = STATE(96),
    [sym_default_statement] = STATE(96),
    [sym_command] = STATE(96),
    [sym_command_type] = STATE(115),
    [sym_track] = STATE(96),
    [sym_track_metadata] = STATE(106),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym__newline] = ACTIONS(9),
    [anon_sym_GT_GT_GT] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_u20ac] = ACTIONS(17),
    [anon_sym_DEFAULT] = ACTIONS(19),
    [anon_sym_COMMAND] = ACTIONS(21),
    [anon_sym_UPDATE_COMMAND] = ACTIONS(21),
    [anon_sym_QUEUE_COMMAND] = ACTIONS(21),
    [sym_address] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [sym_shuttle_content] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym__newline,
    ACTIONS(34), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(37), 1,
      anon_sym_AT,
    ACTIONS(40), 1,
      anon_sym_STAR,
    ACTIONS(43), 1,
      anon_sym_u20ac,
    ACTIONS(46), 1,
      anon_sym_DEFAULT,
    ACTIONS(52), 1,
      sym_address,
    ACTIONS(55), 1,
      anon_sym_LT,
    ACTIONS(58), 1,
      sym_shuttle_content,
    STATE(106), 1,
      sym_track_metadata,
    STATE(112), 1,
      sym_selected,
    STATE(115), 1,
      sym_command_type,
    STATE(2), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    ACTIONS(49), 3,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
    STATE(119), 7,
      sym__statement,
      sym_group_filter,
      sym_synth_header,
      sym_effect_definition,
      sym_default_statement,
      sym_command,
      sym_track,
  [61] = 17,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_GT_GT_GT,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(17), 1,
      anon_sym_u20ac,
    ACTIONS(19), 1,
      anon_sym_DEFAULT,
    ACTIONS(23), 1,
      sym_address,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      sym_shuttle_content,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      sym__newline,
    STATE(106), 1,
      sym_track_metadata,
    STATE(115), 1,
      sym_command_type,
    STATE(117), 1,
      sym_selected,
    STATE(2), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 3,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
    STATE(94), 7,
      sym__statement,
      sym_group_filter,
      sym_synth_header,
      sym_effect_definition,
      sym_default_statement,
      sym_command,
      sym_track,
  [122] = 12,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      sym__newline,
    ACTIONS(69), 1,
      anon_sym_COLON,
    ACTIONS(73), 1,
      aux_sym_arg_name_token1,
    ACTIONS(75), 1,
      sym_number,
    ACTIONS(77), 1,
      sym_additional_config,
    STATE(29), 1,
      sym_arg_name,
    STATE(34), 1,
      sym_arg,
    STATE(65), 1,
      sym_arg_list,
    STATE(113), 1,
      sym_operator,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [162] = 12,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(73), 1,
      aux_sym_arg_name_token1,
    ACTIONS(75), 1,
      sym_number,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym__newline,
    ACTIONS(83), 1,
      anon_sym_COLON,
    ACTIONS(85), 1,
      sym_additional_config,
    STATE(29), 1,
      sym_arg_name,
    STATE(34), 1,
      sym_arg,
    STATE(63), 1,
      sym_arg_list,
    STATE(113), 1,
      sym_operator,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [202] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 12,
      sym__newline,
      anon_sym_GT_GT_GT,
      anon_sym_AT,
      anon_sym_STAR,
      anon_sym_u20ac,
      anon_sym_DEFAULT,
      anon_sym_COMMAND,
      anon_sym_UPDATE_COMMAND,
      anon_sym_QUEUE_COMMAND,
      sym_address,
      anon_sym_LT,
      sym_shuttle_content,
  [223] = 11,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(73), 1,
      aux_sym_arg_name_token1,
    ACTIONS(75), 1,
      sym_number,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      sym__newline,
    ACTIONS(95), 1,
      sym_additional_config,
    STATE(29), 1,
      sym_arg_name,
    STATE(34), 1,
      sym_arg,
    STATE(62), 1,
      sym_arg_list,
    STATE(113), 1,
      sym_operator,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [260] = 11,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(73), 1,
      aux_sym_arg_name_token1,
    ACTIONS(75), 1,
      sym_number,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 1,
      sym__newline,
    ACTIONS(101), 1,
      sym_additional_config,
    STATE(29), 1,
      sym_arg_name,
    STATE(34), 1,
      sym_arg,
    STATE(64), 1,
      sym_arg_list,
    STATE(113), 1,
      sym_operator,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [297] = 11,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym__newline,
    ACTIONS(73), 1,
      aux_sym_arg_name_token1,
    ACTIONS(77), 1,
      sym_additional_config,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(105), 1,
      sym_number,
    STATE(31), 1,
      sym_arg_name,
    STATE(54), 1,
      sym_arg,
    STATE(75), 1,
      sym_arg_list,
    STATE(118), 1,
      sym_operator,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [334] = 11,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(73), 1,
      aux_sym_arg_name_token1,
    ACTIONS(81), 1,
      sym__newline,
    ACTIONS(85), 1,
      sym_additional_config,
    ACTIONS(105), 1,
      sym_number,
    ACTIONS(107), 1,
      anon_sym_COLON,
    STATE(31), 1,
      sym_arg_name,
    STATE(54), 1,
      sym_arg,
    STATE(82), 1,
      sym_arg_list,
    STATE(118), 1,
      sym_operator,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [371] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      aux_sym_arg_name_token1,
    ACTIONS(115), 1,
      sym_number,
    STATE(24), 1,
      sym_arg_name,
    STATE(40), 1,
      sym_arg,
    STATE(79), 1,
      sym_arg_list,
    STATE(107), 1,
      sym_operator,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [403] = 10,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(73), 1,
      aux_sym_arg_name_token1,
    ACTIONS(93), 1,
      sym__newline,
    ACTIONS(95), 1,
      sym_additional_config,
    ACTIONS(105), 1,
      sym_number,
    STATE(31), 1,
      sym_arg_name,
    STATE(54), 1,
      sym_arg,
    STATE(83), 1,
      sym_arg_list,
    STATE(118), 1,
      sym_operator,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [437] = 10,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(73), 1,
      aux_sym_arg_name_token1,
    ACTIONS(99), 1,
      sym__newline,
    ACTIONS(101), 1,
      sym_additional_config,
    ACTIONS(105), 1,
      sym_number,
    STATE(31), 1,
      sym_arg_name,
    STATE(54), 1,
      sym_arg,
    STATE(84), 1,
      sym_arg_list,
    STATE(118), 1,
      sym_operator,
    ACTIONS(71), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [471] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 9,
      sym__newline,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      aux_sym_arg_name_token1,
      sym_number,
      sym_additional_config,
  [489] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      aux_sym_arg_name_token1,
    ACTIONS(115), 1,
      sym_number,
    STATE(24), 1,
      sym_arg_name,
    STATE(40), 1,
      sym_arg,
    STATE(89), 1,
      sym_arg_list,
    STATE(107), 1,
      sym_operator,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [517] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      aux_sym_arg_name_token1,
    ACTIONS(115), 1,
      sym_number,
    STATE(24), 1,
      sym_arg_name,
    STATE(40), 1,
      sym_arg,
    STATE(104), 1,
      sym_arg_list,
    STATE(107), 1,
      sym_operator,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [545] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      aux_sym_arg_name_token1,
    ACTIONS(115), 1,
      sym_number,
    STATE(24), 1,
      sym_arg_name,
    STATE(49), 1,
      sym_arg,
    STATE(107), 1,
      sym_operator,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [570] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      aux_sym_arg_name_token1,
    ACTIONS(121), 1,
      sym_number,
    STATE(29), 1,
      sym_arg_name,
    STATE(46), 1,
      sym_arg,
    STATE(113), 1,
      sym_operator,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [595] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 8,
      sym__newline,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      aux_sym_arg_name_token1,
      sym_number,
      sym_additional_config,
  [612] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(119), 9,
      sym__newline,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      aux_sym_arg_name_token1,
      sym_number,
      sym_additional_config,
  [627] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      aux_sym_arg_name_token1,
    ACTIONS(127), 1,
      sym_number,
    STATE(31), 1,
      sym_arg_name,
    STATE(70), 1,
      sym_arg,
    STATE(118), 1,
      sym_operator,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [652] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(125), 8,
      sym__newline,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      aux_sym_arg_name_token1,
      sym_number,
      sym_additional_config,
  [666] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 1,
      aux_sym_arg_name_token1,
    STATE(50), 1,
      sym_ref,
    ACTIONS(131), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [684] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_number,
    STATE(100), 1,
      sym_operator,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [700] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(133), 1,
      aux_sym_arg_name_token1,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    STATE(48), 1,
      sym_ref,
    ACTIONS(139), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [718] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      aux_sym_arg_name_token1,
    STATE(59), 1,
      sym_ref,
    ACTIONS(129), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [734] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(133), 1,
      aux_sym_arg_name_token1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    STATE(44), 1,
      sym_ref,
    ACTIONS(145), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [752] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      aux_sym_arg_name_token1,
    STATE(57), 1,
      sym_ref,
    ACTIONS(143), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [768] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym_number,
    STATE(116), 1,
      sym_operator,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [784] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      aux_sym_arg_name_token1,
    STATE(45), 1,
      sym_ref,
    ACTIONS(137), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [800] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_number,
    STATE(120), 1,
      sym_operator,
    ACTIONS(111), 4,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
  [816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
  [831] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      aux_sym_group_override_token1,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      sym__newline,
    STATE(36), 2,
      sym_group_name,
      aux_sym_group_filter_repeat1,
  [846] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(162), 2,
      sym__newline,
      sym_additional_config,
  [863] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(168), 2,
      sym__newline,
      sym_additional_config,
  [880] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      aux_sym_group_override_token1,
    ACTIONS(170), 2,
      ts_builtin_sym_end,
      sym__newline,
    STATE(36), 2,
      sym_group_name,
      aux_sym_group_filter_repeat1,
  [895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 5,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      sym_number,
  [906] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
  [921] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(179), 2,
      sym__newline,
      sym_additional_config,
  [938] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(160), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
  [953] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(184), 1,
      aux_sym_arg_name_token1,
    STATE(71), 1,
      sym_ref,
    ACTIONS(139), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [968] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(184), 1,
      aux_sym_arg_name_token1,
    STATE(72), 1,
      sym_ref,
    ACTIONS(131), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [983] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(184), 1,
      aux_sym_arg_name_token1,
    STATE(69), 1,
      sym_ref,
    ACTIONS(145), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [998] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1010] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1020] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(179), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1042] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1064] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    ACTIONS(190), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1076] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    ACTIONS(194), 1,
      sym__newline,
    ACTIONS(196), 1,
      sym_command_arg,
    STATE(51), 1,
      aux_sym_command_repeat1,
  [1092] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 1,
      sym__newline,
    ACTIONS(203), 1,
      sym_command_arg,
    STATE(61), 1,
      aux_sym_command_repeat1,
  [1108] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1120] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(162), 2,
      sym__newline,
      sym_additional_config,
  [1134] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
    ACTIONS(211), 1,
      sym__newline,
    ACTIONS(213), 1,
      sym_command_arg,
    STATE(51), 1,
      aux_sym_command_repeat1,
  [1150] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(168), 2,
      sym__newline,
      sym_additional_config,
  [1164] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1174] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(179), 2,
      sym__newline,
      sym_additional_config,
  [1188] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_GT,
      anon_sym_COMMA,
  [1198] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
    ACTIONS(220), 1,
      sym__newline,
    ACTIONS(222), 1,
      sym_command_arg,
    STATE(55), 1,
      aux_sym_command_repeat1,
  [1214] = 5,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_command_arg,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
    ACTIONS(220), 1,
      sym__newline,
    STATE(51), 1,
      aux_sym_command_repeat1,
  [1230] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 1,
      sym__newline,
    ACTIONS(101), 1,
      sym_additional_config,
  [1243] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      sym__newline,
    ACTIONS(95), 1,
      sym_additional_config,
  [1256] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
    ACTIONS(226), 1,
      sym__newline,
    ACTIONS(228), 1,
      sym_additional_config,
  [1269] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym__newline,
    ACTIONS(85), 1,
      sym_additional_config,
  [1282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      sym__newline,
      aux_sym_group_override_token1,
  [1291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      aux_sym_group_override_token1,
    STATE(33), 2,
      sym_group_name,
      aux_sym_group_filter_repeat1,
  [1302] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(205), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1311] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(139), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1320] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(179), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1329] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(131), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1338] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(190), 3,
      sym__newline,
      anon_sym_COMMA,
      sym_additional_config,
  [1347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      aux_sym_group_override_token1,
    STATE(10), 1,
      sym_instrument_name,
  [1365] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym__newline,
    ACTIONS(85), 1,
      sym_additional_config,
  [1375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      aux_sym_group_override_token1,
    STATE(7), 1,
      sym_group_name,
  [1385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_SEMI,
    ACTIONS(238), 1,
      anon_sym_GT,
  [1403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1411] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      aux_sym_group_override_token1,
    STATE(105), 1,
      sym_effect_type,
  [1421] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      aux_sym_group_override_token1,
    STATE(5), 1,
      sym_instrument_name,
  [1431] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym__newline,
    ACTIONS(95), 1,
      sym_additional_config,
  [1441] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym__newline,
    ACTIONS(101), 1,
      sym_additional_config,
  [1451] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym__newline,
    ACTIONS(228), 1,
      sym_additional_config,
  [1461] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      aux_sym_group_override_token1,
    STATE(4), 1,
      sym_instrument_name,
  [1471] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      aux_sym_group_override_token1,
    STATE(78), 1,
      sym_group_override,
  [1481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1505] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      aux_sym_group_override_token1,
    STATE(8), 1,
      sym_group_name,
  [1523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1539] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      ts_builtin_sym_end,
    ACTIONS(256), 1,
      sym__newline,
  [1549] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      aux_sym_group_override_token1,
    STATE(9), 1,
      sym_instrument_name,
  [1559] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(256), 1,
      sym__newline,
  [1569] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      aux_sym_group_override_token1,
    STATE(12), 1,
      sym_group_name,
  [1579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      aux_sym_group_override_token1,
    STATE(13), 1,
      sym_group_name,
  [1589] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 2,
      anon_sym_SEMI,
      anon_sym_GT,
  [1597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_number,
  [1604] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_shuttle_content,
  [1611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_address,
  [1618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_COLON,
  [1625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_GT,
  [1632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_COLON,
  [1639] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_shuttle_content,
  [1646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_number,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_AT,
  [1660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      ts_builtin_sym_end,
  [1667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_number,
  [1674] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_shuttle_content,
  [1681] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_AT,
  [1688] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym_number,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_effect_id,
  [1702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      sym_address,
  [1709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      sym_number,
  [1716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_AT,
  [1723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_number,
  [1730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym__newline,
  [1737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 122,
  [SMALL_STATE(5)] = 162,
  [SMALL_STATE(6)] = 202,
  [SMALL_STATE(7)] = 223,
  [SMALL_STATE(8)] = 260,
  [SMALL_STATE(9)] = 297,
  [SMALL_STATE(10)] = 334,
  [SMALL_STATE(11)] = 371,
  [SMALL_STATE(12)] = 403,
  [SMALL_STATE(13)] = 437,
  [SMALL_STATE(14)] = 471,
  [SMALL_STATE(15)] = 489,
  [SMALL_STATE(16)] = 517,
  [SMALL_STATE(17)] = 545,
  [SMALL_STATE(18)] = 570,
  [SMALL_STATE(19)] = 595,
  [SMALL_STATE(20)] = 612,
  [SMALL_STATE(21)] = 627,
  [SMALL_STATE(22)] = 652,
  [SMALL_STATE(23)] = 666,
  [SMALL_STATE(24)] = 684,
  [SMALL_STATE(25)] = 700,
  [SMALL_STATE(26)] = 718,
  [SMALL_STATE(27)] = 734,
  [SMALL_STATE(28)] = 752,
  [SMALL_STATE(29)] = 768,
  [SMALL_STATE(30)] = 784,
  [SMALL_STATE(31)] = 800,
  [SMALL_STATE(32)] = 816,
  [SMALL_STATE(33)] = 831,
  [SMALL_STATE(34)] = 846,
  [SMALL_STATE(35)] = 863,
  [SMALL_STATE(36)] = 880,
  [SMALL_STATE(37)] = 895,
  [SMALL_STATE(38)] = 906,
  [SMALL_STATE(39)] = 921,
  [SMALL_STATE(40)] = 938,
  [SMALL_STATE(41)] = 953,
  [SMALL_STATE(42)] = 968,
  [SMALL_STATE(43)] = 983,
  [SMALL_STATE(44)] = 998,
  [SMALL_STATE(45)] = 1010,
  [SMALL_STATE(46)] = 1020,
  [SMALL_STATE(47)] = 1032,
  [SMALL_STATE(48)] = 1042,
  [SMALL_STATE(49)] = 1054,
  [SMALL_STATE(50)] = 1064,
  [SMALL_STATE(51)] = 1076,
  [SMALL_STATE(52)] = 1092,
  [SMALL_STATE(53)] = 1108,
  [SMALL_STATE(54)] = 1120,
  [SMALL_STATE(55)] = 1134,
  [SMALL_STATE(56)] = 1150,
  [SMALL_STATE(57)] = 1164,
  [SMALL_STATE(58)] = 1174,
  [SMALL_STATE(59)] = 1188,
  [SMALL_STATE(60)] = 1198,
  [SMALL_STATE(61)] = 1214,
  [SMALL_STATE(62)] = 1230,
  [SMALL_STATE(63)] = 1243,
  [SMALL_STATE(64)] = 1256,
  [SMALL_STATE(65)] = 1269,
  [SMALL_STATE(66)] = 1282,
  [SMALL_STATE(67)] = 1291,
  [SMALL_STATE(68)] = 1302,
  [SMALL_STATE(69)] = 1311,
  [SMALL_STATE(70)] = 1320,
  [SMALL_STATE(71)] = 1329,
  [SMALL_STATE(72)] = 1338,
  [SMALL_STATE(73)] = 1347,
  [SMALL_STATE(74)] = 1355,
  [SMALL_STATE(75)] = 1365,
  [SMALL_STATE(76)] = 1375,
  [SMALL_STATE(77)] = 1385,
  [SMALL_STATE(78)] = 1393,
  [SMALL_STATE(79)] = 1403,
  [SMALL_STATE(80)] = 1411,
  [SMALL_STATE(81)] = 1421,
  [SMALL_STATE(82)] = 1431,
  [SMALL_STATE(83)] = 1441,
  [SMALL_STATE(84)] = 1451,
  [SMALL_STATE(85)] = 1461,
  [SMALL_STATE(86)] = 1471,
  [SMALL_STATE(87)] = 1481,
  [SMALL_STATE(88)] = 1489,
  [SMALL_STATE(89)] = 1497,
  [SMALL_STATE(90)] = 1505,
  [SMALL_STATE(91)] = 1513,
  [SMALL_STATE(92)] = 1523,
  [SMALL_STATE(93)] = 1531,
  [SMALL_STATE(94)] = 1539,
  [SMALL_STATE(95)] = 1549,
  [SMALL_STATE(96)] = 1559,
  [SMALL_STATE(97)] = 1569,
  [SMALL_STATE(98)] = 1579,
  [SMALL_STATE(99)] = 1589,
  [SMALL_STATE(100)] = 1597,
  [SMALL_STATE(101)] = 1604,
  [SMALL_STATE(102)] = 1611,
  [SMALL_STATE(103)] = 1618,
  [SMALL_STATE(104)] = 1625,
  [SMALL_STATE(105)] = 1632,
  [SMALL_STATE(106)] = 1639,
  [SMALL_STATE(107)] = 1646,
  [SMALL_STATE(108)] = 1653,
  [SMALL_STATE(109)] = 1660,
  [SMALL_STATE(110)] = 1667,
  [SMALL_STATE(111)] = 1674,
  [SMALL_STATE(112)] = 1681,
  [SMALL_STATE(113)] = 1688,
  [SMALL_STATE(114)] = 1695,
  [SMALL_STATE(115)] = 1702,
  [SMALL_STATE(116)] = 1709,
  [SMALL_STATE(117)] = 1716,
  [SMALL_STATE(118)] = 1723,
  [SMALL_STATE(119)] = 1730,
  [SMALL_STATE(120)] = 1737,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 5, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 5, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_definition, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instrument_name, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instrument_name, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_name, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_name, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_filter, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_filter_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_filter_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_name, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 4, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 4, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 6, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_synth_header, 6, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track, 1, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_definition, 5, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_statement, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_synth_header, 7, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track, 2, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_override, 1, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track_metadata, 5, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_type, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_type, 1, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selected, 1, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track_metadata, 3, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jdw_billboarding(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jdw_billboarding",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
